python inceptionism.py \
  --image_type=amplify_layer \
  --target_layer=inception_4b/5x5_reduce \
  --gpu=0 \
  --num_steps=100 \
  --batch_size=25 \
  --output_iter=10 \
  --learning_rate=5.0 \
  --decay_rate=0.85 \
  --alpha=2.0 \
  --p_reg=5e-1 \
  --alpha_aux=8.0 \
  --p_reg_aux=5e-11 \
  --use_pixel_learning_rates \
  --beta=2.5 \
  --tv_reg=5e-1 \
  --initial_image=initial_imgs/bliss.jpg \
  --initial_size=x0.25 \
  --final_size=x0.5 \
  --num_sizes=3 \
  --iter_behavior=print \
  --output_file=example13.png
